name: Main

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: ruby:2.3.8

    strategy:
      fail-fast: false

    steps:
      - uses: actions/checkout@v2
      
      - name: Bundle install
        env:
          RAILS_ENV: test
        run: |
          gem install bundler
          bundle install

      - name: Run tests
        run: |
          bundle exec rspec